apiVersion: operator.example.com/v1alpha2
kind: NginxOperator
metadata:
  labels:
    app.kubernetes.io/name: nginx-operator
    app.kubernetes.io/managed-by: kustomize
  name: nginxoperator-sample
spec:
  replicas: 1
  ports:
    - 8080
